services:
  mariadb:
    image: mariadb:11.4
    container_name: dev-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: appsecret
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci"
    ]
    ports:
      - "3307:3306"   # 로컬 3307로 노출 (3306 쓰는 중일 수 있어서)
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: dev-adminer
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
